FROM unicon/shibboleth-idp@sha256:f16dcc80e237b0ae14dfcdac2a93c049d4992bb86f26220480f2814e872b7a70

MAINTAINER Unicon, Inc.

COPY shibboleth-idp/ /opt/shibboleth-idp/
COPY shib-jetty-base/ /opt/shib-jetty-base/
