name: pass-acceptance-testing

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  TIMEOUT_LENGTH: 120000

jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Append hosts file
      run: echo "127.0.0.1    pass.local" | sudo tee -a /etc/hosts

    - name: Checkout pass-docker
      uses: actions/checkout@v3

    # The '--wait' flag will wait for the pass-core healthcheck
    - name: Run pass-docker
      run: docker compose up -d --quiet-pull --no-build --wait

    - name: Checkout pass-acceptance-testing
      uses: actions/checkout@v3
      with:
        repository: eclipse-pass/pass-acceptance-testing
        path: pass-acceptance-testing

    - name: Run acceptance tests
      uses: DevExpress/testcafe-action@latest
      with:
        args: "chrome ./pass-acceptance-testing/tests/*Tests.js --selector-timeout 60000 --assertion-timeout 60000 --ajax-request-timeout 60000"
